version: '3.8'

services:
  mysql_test:
    image: mysql:8.0
    container_name: mysql_test
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: thinkhuge_test
      MYSQL_USER: thinkhuge
      MYSQL_PASSWORD: thinkhuge
    ports:
      - "3307:3306"
    volumes:
      - ./database/db_test:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
